### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by skefy** [rangerzhou/HomeAssistant#2]
2020-03-15 14:43:40 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/home/firefly/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "/home/firefly/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    state = self.state
  File "/home/firefly/homeassistant/lib/python3.7/site-packages/homeassistant/components/weather/__init__.py", line 187, in state
    return self.condition
  File "/home/firefly/.homeassistant/custom_components/heweather_forecast/weather.py", line 136, in condition
    self._condition in v][0]
IndexError: list index out of range

**Comment by skefy** [comment]
Done！
原因是我开了代理

**Comment by sunlu834199** [comment]
Platform error weather.hf_weather - Integration 'hf_weather' not found.
